Repository datafold/data-diff, pull requests merged in 2023-08, with the labels that each got.

#664 check for interactive session before email prompt
  data_diff/tracking.py
Labels: bug, --dbt

#653 Fix type handling of `key_columns` in toml
  data_diff/config.py
  tests/test_config.py
Labels: bug

#662 Fix for more than 50 fields in Postgres
  data_diff/sqeleton/databases/postgresql.py
  tests/test_postgresql.py
Labels: bug

#682 partial --select support for dbt < 1.5
  data_diff/__main__.py
  data_diff/dbt_parser.py
  data_diff/errors.py
  tests/test_dbt_parser.py
Labels: enhancement, --dbt

#685 bump parser and data-diff versions
  data_diff/version.py
  poetry.lock
  pyproject.toml
Labels: bug, --dbt
