Repository datafold/data-diff, pull requests merged in 2023-10, with the labels that each got.

#732 adjust DatafoldAPI for attrs
  data_diff/cloud/datafold_api.py
Labels: bug, cloud, --dbt

#734 Check if `test_metadata` Exists First
  data_diff/dbt_parser.py
Labels: bug

#716 Make DuckDB data diffs work better
  README.md
  data_diff/__main__.py
  data_diff/joindiff_tables.py
  data_diff/utils.py
  tests/test_joindiff.py
  tests/test_utils.py
Labels: enhancement

#737 AbstractMixin_MD5->Mixin_MD5 to override pg version
  data_diff/databases/redshift.py
Labels: bug
